# Generated by Django 3.1.7 on 2021-08-13 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(blank=True, default=None, upload_to=None)),
            ],
        ),
    ]
