# Generated by Django 3.1.7 on 2021-08-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EQuest', '0002_auto_20210814_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content1',
            new_name='contentA',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content2',
            new_name='contentB',
        ),
    ]
