# Generated by Django 3.1.7 on 2021-08-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EQuest', '0003_auto_20210814_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentA',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentB',
            field=models.TextField(default=False),
        ),
    ]
