# Generated by Django 3.1.7 on 2021-08-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EQuest', '0004_auto_20210814_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contentA',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentB',
        ),
    ]
