# Generated by Django 3.2.6 on 2021-09-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EQuest', '0006_auto_20210814_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.RenameField(
            model_name='post',
            old_name='genre',
            new_name='category',
        ),
    ]
