# Generated by Django 3.2.6 on 2021-09-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EQuest', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
    ]
