# Generated by Django 3.0.2 on 2021-12-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reponsibliity',
            options={'verbose_name_plural': 'Responsiblities'},
        ),
    ]
