# Generated by Django 3.0.2 on 2021-12-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0003_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reponsibliity',
            new_name='Responsibliity',
        ),
    ]
