# Generated by Django 3.0.2 on 2021-12-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0004_auto_20211229_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='icon_class',
            field=models.CharField(default='money-check-alt', max_length=50),
            preserve_default=False,
        ),
    ]
