# Generated by Django 3.0.8 on 2020-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('position', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(upload_to='memberImages/')),
                ('year', models.IntegerField(default=None)),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
