# Generated by Django 3.0.8 on 2020-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(null=True, upload_to='memberImages/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
