# Generated by Django 3.0.8 on 2020-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200727_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='members',
            name='facebook',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='memberImages/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='linkedin',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
