# Generated by Django 3.0.8 on 2020-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=15)),
                ('aboutevent', models.TextField()),
                ('img1', models.ImageField(default='', upload_to=None)),
                ('img2', models.ImageField(default='', upload_to=None)),
                ('img3', models.ImageField(default='', upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=15)),
                ('about_event', models.TextField()),
                ('image1', models.ImageField(default='', upload_to=None)),
                ('image2', models.ImageField(default='', upload_to=None)),
                ('image3', models.ImageField(default='', upload_to=None)),
            ],
        ),
    ]
